### ISSUE TITLE
Create Kanban Board for our capstone

### ISSUE THREAD

**Issue by naji-97** [Yacoubou-seidou/RoR_Group_Project#11]
**A team consisting of two members:**

- [ ] @Yacoubou-seidou 
- [ ] @naji-97 
- [ ] Link to the project:  https://github.com/users/Yacoubou-seidou/projects/1

**Comment by Owusu-Desmond** [comment]
Hi @naji-97 and @Yacoubou-seidou , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
📌 Descriptive issue ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please make sure that you don't have to two repeated card title but as you can see below you have repeated task title with the same task description and one will not know if these task are different or no so kindly make your these titles descriptive if they are different task like `Fix N+1 queries for Food list` and `Fix N+1 queries for recipe list` or you can make these two task a single task as `Fix N+1 queries` and assign it as group task. :blush: 

  ![Screenshot from 2023-07-31 13-37-00](https://github.com/Yacoubou-seidou/RoR_Group_Project/assets/92303891/7969fdb6-1271-48f7-a502-0bb6f6fb7899)


- [ ] I can see all your task card have number of points in the [Xpt] :+1:  but as not prefix so please make the points prefix as you can see below :point_down: 
  
  ![image](https://github.com/Yacoubou-seidou/RoR_Group_Project/assets/92303891/2a16c2c8-c2e9-4c83-9ebd-30ca75b87367)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yacoubou-seidou** [comment]
Required changes made

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @Yacoubou-seidou, and @naji-97👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
